<?php

namespace HolidayBundle\Repository;

/**
 * ApprovalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalRepository extends \Doctrine\ORM\EntityRepository
{
}
