<?php

namespace HolidayBundle\Repository;

/**
 * HolidayTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
