<?php

namespace HolidayBundle\Repository;

/**
 * HolidayStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayStockRepository extends \Doctrine\ORM\EntityRepository
{
}
