<?php

namespace HolidayBundle\Repository;

/**
 * HolidayRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
