<?php

namespace HolidayBundle\Repository;

/**
 * JobLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
