<?php

namespace HolidayBundle\Repository;

/**
 * ValideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValideRepository extends \Doctrine\ORM\EntityRepository
{
}
